ALTER TABLE Film
DROP COLUMN Director,
DROP COLUMN DirectorCountry,
DROP COLUMN Star,
DROP COLUMN StarDOB,
DROP COLUMN Writer,
DROP COLUMN WriterEmail;

ALTER TABLE Film
    ADD COLUMN DirectorID INT,
ADD COLUMN StarID INT,
ADD COLUMN WriterID INT;

ALTER TABLE Film
    ADD CONSTRAINT FK_DirectorID FOREIGN KEY (DirectorID) REFERENCES Director(DirectorID),
ADD CONSTRAINT FK_StarID FOREIGN KEY (StarID) REFERENCES Star(StarID),
ADD CONSTRAINT FK_WriterID FOREIGN KEY (WriterID) REFERENCES Writer(WriterID);