CREATE TABLE Cast (
    ID SERIAL PRIMARY KEY,
    MovieID INT REFERENCES Movies(ID),
    ActorID INT REFERENCES People(ID)
);

ALTER TABLE Cast
ADD CONSTRAINT FK_MovieID FOREIGN KEY (MovieID) REFERENCES Movies(ID),
ADD CONSTRAINT FK_ActorID FOREIGN KEY (ActorID) REFERENCES People(ID);
