CREATE TABLE IF NOT EXISTS Genre(
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT
);

ALTER TABLE Movies
DROP COLUMN IF EXISTS genre,
DROP COLUMN IF EXISTS genre_id;

ALTER TABLE Movies
ADD COLUMN IF NOT EXISTS genre_id BIGINT(20) unsigned;

ALTER TABLE Movies
ADD FOREIGN KEY IF NOT EXISTS (genre_id) REFERENCES Genre(id);
