INSERT INTO Persons (name) VALUES
    ('Stanley Kubrick'),
    ('Keir Dullea'),
    ('Arthur C Clarke'),
    ('George Lucas'),
    ('Mark Hamill'),
    ('Robert Mulligan'),
    ('Gregory Peck'),
    ('Harper Lee'),
    ('James Cameron'),
    ('Leonardo DiCaprio'),
    ('Julie Christie'),
    ('Boris Pasternak'),
    ('Anthony Mann'),
    ('Charlton Heston'),
    ('Frederick Frank'),
    ('Theodoros Angelopoulos'),
    ('Manos Katrakis'),
    ('Rutger Hauer'),
    ('Erik Hazelhoff Roelfzema'),
    ('Krzysztof Kieslowski'),
    ('Juliette Binoche'),
    ('Jean-Paul Rappeneau'),
    ('Gerard Depardieu'),
    ('David Lean'),
    ('Paul Verhoeven'),
    ('Edmond Rostand');

