INSERT INTO people
    (name)
VALUES
    ('Stanley Kubrick'),
    ('Keir Dullea'),
    ('Arthur C Clarke'),
    ('George Lucas'),
    ('Mark Hamill'),
    ('Robert Mulligan'),
    ('Gregory Peck'),
    ('Harper Lee'),
    ('James Cameron'),
    ('Leonardo DiCaprio'),
    ('David Lean'),
    ('Julie Christie'),
    ('Boris Pasternak'),
    ('Anthony Mann'),
    ('Charlton Heston'),
    ('Frederick Frank'),
    ('Theodoros Angelopoulos'),
    ('Manos Katrakis'),
    ('Paul Verhoeven'),
    ('Rutger Hauer'),
    ('Erik Hazelhoff Roelfzema'),
    ('Krzysztof Kieslowski'),
    ('Juliette Binoche'),
    ('Jean-Paul Rappeneau'),
    ('Gerard Depardieu'),
    ('Edmond Rostand');