insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('2001: A Space Odyssey', 1968, 'Science Fiction', 10, 1, 1, 61);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('Star Wars: A New Hope', 1977, 'Science Fiction', 7, 2, 2, 2);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('To Kill A Mockingbird', 1962, 'Drama', 10, 3, 3, 3);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('Titanic', 1997, 'Romance', 5, 4, 4, 4);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('Dr Zhivago', 1965, 'Historical', 8, 5, 5, 5);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('El Cid', 1961, 'Historical', 6, 6, 6, 66);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('Voyage to Cythera', 1984, 'Drama', 8, 7, 7, 7);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('Soldier of Orange', 1977, 'Thriller', 8, 8, 8, 8);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('Three Colours: Blue', 1993, 'Drama', 8, 9, 9, 9);
insert into Films(title, year, genre, score, director_id, star_id, writer_id) VALUES('Cyrano de Bergerac', 1990, 'Historical', 9, 10, 10, 10);
