INSERT INTO people (name)
	VALUES
		('Stanley Kubrick'),
		('George Lucas'),
		('Robert Mulligan'),
		('James Cameron'),
		('David Lean'),
		('Anthony Mann'),
		('Theodoros Angelopoulos'),
		('Paul Verhoeven'),
		('Krzysztof Kieslowski'),
		('Jean-Paul Rappeneau'),
		('Keir Dullea'),
		('Mark Hamill'),
		('Gregory Peck'),
		('Leonardo DiCaprio'),
		('Julie Christie'),
		('Charlton Heston'),
		('Manos Katrakis'),
		('Rutger Hauer'),
		('Juliette Binoche'),
		('Gerard Depardieu'),
		('Arthur C Clarke'),
		('Harper Lee'),
		('Boris Pasternak'),
		('Frederick Frank'),
		('Erik Hazelhoff Roelfzema'),
		('Edmond Rostand');