INSERT INTO actors
    (name, character_name, film_id)
VALUES
    ('Keir Dullea', 'David Bowman', 1),
    ('Gary Lockwood', 'Dr. Frank Poole', 1),
    ('Daniel Richter', 'Moon-Watcher', 1),
    ('Mark Hamill', 'Luke Skywalker', 2),
    ('Harrison Ford', 'Han Solo', 2),
    ('Carrie Fisher', 'Princess Leia', 2),
    ('Gregory Peck', 'Atticus Finch', 3),
    ('Mary Badham', 'Jean Louise Scout Finch', 3),
    ('Phillip Alford', 'Jem Finch', 3),
    ('Leonardo DiCaprio', 'Jack Dawson', 4),
    ('Kate Winslet', 'Rose Dewitt Bukater', 4),
    ('Billy Zane', 'Cal Hockley', 4),
    ('Omar Sharif', 'Yuri', 5),
    ('Julie Christie', 'Lara', 5),
    ('Geraldine Chaplin', 'Tonya', 5),
    ('Charlton Heston', 'El Cid Rodrigo de Vivar', 6),
    ('Sophia Loren', 'Jimena', 6),
    ('Raf Vallone', 'Count Ordonez', 6),
    ('Manos Katrakis', 'Spyros', 7),
    ('Mary Hronopoulou', 'Voula', 7),
    ('Dionysis Papagiannopoulos', 'Antonis', 7),
    ('Rutger Hauer', 'Erik Lanshof', 8),
    ('Jeroen Krabbe', 'Guus LeJeune', 8),
    ('Susan Penhaligon', 'Susan', 8),
    ('Juliette Binoche', 'Julie', 9),
    ('Zbigniew Zamachowski', 'Karol Karol', 9),
    ('Julie Delpy', 'Dominique', 9),
    ('Gerard Depardieu', 'Cyrano De Bergerac', 10),
    ('Anne Brochet', 'Roxane', 10),
    ('Vincent Perez', 'Christian de Neuvillette', 10);