CREATE TABLE films(
id SERIAL PRIMARY KEY,
title VARCHAR(255) UNIQUE NOT NULL,
director VARCHAR(255) NOT NULL,
director_country VARCHAR(50) NOT NULL,
star VARCHAR(255) NOT NULL,
star_dob DATE NOT NULL,
writer VARCHAR(255) NOT NULL,
writer_email VARCHAR(255) UNIQUE NOT NULL,
release_year INT NOT NULL,
genre VARCHAR(50) NOT NULL,
score INT NOT NULL
);